-- 0010: Audit trail + booking idempotency.
--
-- 1. booking_event: immutable, append-only audit table for the complete
--    booking history. previousBookingId alone is not sufficient: reschedules,
--    cancellations, approvals, and no-shows all need an explicit, queryable
--    record with actor and metadata. Rows are never updated or deleted by
--    application code.
--
-- 2. bookings.idempotency_key: unique per-submission key generated by the
--    client. Repeated submissions (double-click, retried request after
--    timeout/5xx/connection reset) return the original booking instead of
--    creating a duplicate. Nullable because historical rows predate the key
--    and admin-created bookings may not carry one.
--
-- Forward-only; no existing rows are modified.

CREATE TABLE IF NOT EXISTS "booking_event" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "booking_id" uuid NOT NULL REFERENCES "bookings"("id") ON DELETE cascade,
  "event_type" varchar(50) NOT NULL, -- 'created' | 'rescheduled' | 'cancelled' | 'approved' | 'rejected' | 'completed' | 'no_show' | 'status_changed'
  "actor_type" varchar(20) NOT NULL DEFAULT 'system', -- 'customer' | 'admin' | 'system'
  "actor_id" uuid, -- users.id for customer/admin, null for system
  "related_booking_id" uuid, -- e.g. replacement booking for a reschedule
  "metadata" text, -- JSON: { oldDate, newDate, reason, ... }
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "booking_event_booking_id_idx" ON "booking_event" ("booking_id");
CREATE INDEX IF NOT EXISTS "booking_event_related_booking_id_idx" ON "booking_event" ("related_booking_id");
CREATE INDEX IF NOT EXISTS "booking_event_created_at_idx" ON "booking_event" ("created_at");

ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "idempotency_key" varchar(64);

-- Unique so a retried submission maps back to the original booking. Partial:
-- only rows that actually carry a key participate, keeping legacy rows valid.
CREATE UNIQUE INDEX IF NOT EXISTS "bookings_idempotency_key_unique"
  ON "bookings" ("idempotency_key")
  WHERE "idempotency_key" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "bookings_idempotency_key_idx" ON "bookings" ("idempotency_key");
